# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_auto_20170705_0114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='id',
        ),
        migrations.AddField(
            model_name='subscription',
            name='uid',
            field=models.UUIDField(default='a1e2a875e2ad46bba52dac2a720d055e', editable=False, primary_key=True, serialize=False),
        ),
    ]
