# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_auto_20170705_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='uid',
            field=models.UUIDField(default='a036d1a7443b42928f90f33ceb16b0e0', editable=False, primary_key=True, serialize=False),
        ),
    ]
