# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_auto_20170707_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Pago'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='uid',
            field=models.UUIDField(default='b07c249b4c65418c9ee714de4c7cdea0', editable=False, primary_key=True, serialize=False),
        ),
    ]
